# Example for parameters to excecute

# I/O
io_parameters:
  data_tiled_uri: https://tiled-seg.als.lbl.gov/api/v1/metadata/reconstruction/rec20190524_085542_clay_testZMQ_8bit/20190524_085542_clay_testZMQ_
  data_tiled_api_key: 
  mask_tiled_uri: https://tiled-seg.als.lbl.gov/api/v1/metadata/mlex_store/mlex_segm_user/rec20190524_085542_clay_testZMQ_8bit/a558f7b1773855b9453bf6c91079699d
  mask_tiled_api_key: 
  seg_tiled_uri: http://0.0.0.0:8888/api/v1/metadata/mlex_store/rec20190524_085542_clay_testZMQ_8bit/results
  seg_tiled_api_key: 
  uid: uid0020

model_parameters:
  network: "TUNet3+"
  num_classes: 3
  num_epochs: 3
  optimizer: "Adam"
  criterion: "CrossEntropyLoss"
  weights: [1, 2, 4]
  learning_rate: 0.1
  activation: "ReLU"
  normalization: "BatchNorm2d"
  convolution: "Conv2d"

  qlty_window: 512
  qlty_step: 100
  qlty_border: 3
  
  shuffle_train: True
  batch_size_train: 1

  batch_size_val: 1

  batch_size_inference: 1
  val_pct: 0.2

  depth: 4
  base_channels: 8
  growth_rate: 2
  hidden_rate: 1
  carryover_channels: 8
