# Example for parameters to excecute

# I/O
io_parameters:
  data_tiled_uri: "http://data/tiled/uri"
  data_tiled_api_key: a1b2c3
  mask_tiled_uri: "http://mask/tiled/uri"
  mask_tiled_api_key: d4e5f6
  seg_tiled_uri: "http://seg/tiled/uri"
  seg_tiled_api_key: g7h8i9
  uid_save: pytest4
  uid_retrieve: pytest4
  models_dir: .

model_parameters:
  network: "DLSIA SMSNetEnsemble"
  num_classes: 2
  num_epochs: 2
  optimizer: "Adam"
  criterion: "CrossEntropyLoss"
  weights: "[2.0, 0.1]"
  learning_rate: 0.1
  activation: "ReLU"
  normalization: "BatchNorm2d"
  convolution: "Conv2d"

  qlty_window: 4
  qlty_step: 2
  qlty_border: 1

  shuffle_train: True
  batch_size_train: 1

  batch_size_val: 1

  batch_size_inference: 2
  val_pct: 0.2

  num_networks: 2
  layers: 3
  alpha: 0.0
  gamma: 0.0
  hidden_channels: null
  dilation_choices: "[1, 2, 3]"
  max_trial: 2
